server:
  port: 8081
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyweibo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.easyweibo.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: easyweibo-secret-key
  expiration: 86400000 # 24小时

# 文件上传路径配置
file:
  upload:
    path: upload/
    allowed-types: image/jpeg,image/png,image/gif,video/mp4
    max-size: 10485760 # 10MB
